<a href="https://colab.research.google.com/github/lilasu086/Individual_CodingProject/blob/main/SupplyChain_DemandUnconstraining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Part I: Demand Unconstraining: Physical products with limited inventory

In [ ]:
import pandas as pd
import numpy as np

grocery_old = pd.read_excel('/content/grocery_data.xlsx')
grocery_old.head(10)

,Unnamed: 0,Hourly interval,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Total
0,Day,1,2,3,4,5,6,7,8,9.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0,NaN
1,1,2,4,4,2,4,2,4,1,5.0,4.0,5.0,3.0,NaN,NaN,NaN,NaN,40.0
2,2,3,4,4,5,4,5,4,2,4.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,40.0
3,3,1,3,2,2,3,6,4,2,3.0,3.0,3.0,4.0,2.0,2.0,NaN,NaN,40.0
4,4,2,3,4,1,4,3,3,1,3.0,3.0,4.0,2.0,3.0,2.0,2.0,NaN,40.0
5,5,2,5,5,3,5,5,5,2,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,40.0
6,6,1,3,3,1,3,3,2,1,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,31.0
7,7,3,4,3,2,4,5,5,3,2.0,4.0,3.0,2.0,NaN,NaN,NaN,NaN,40.0
8,8,1,2,2,1,1,1,2,1,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,20.0
9,9,1,2,3,2,2,2,2,1,2.0,2.0,2.0,2.0,2.0,3.0,2.0,1.0,31.0

In [ ]:
grocery_old = grocery_old.iloc[1:,1:18]
grocery_old.columns = np.arange(1,18)
grocery_old = grocery_old.rename(columns={17:'Total'})
grocery_old

    1  2  3  4  5  6  7  8    9   10   11   12   13   14   15   16  Total
1   2  4  4  2  4  2  4  1  5.0  4.0  5.0  3.0  NaN  NaN  NaN  NaN   40.0
2   3  4  4  5  4  5  4  2  4.0  5.0  NaN  NaN  NaN  NaN  NaN  NaN   40.0
3   1  3  2  2  3  6  4  2  3.0  3.0  3.0  4.0  2.0  2.0  NaN  NaN   40.0
4   2  3  4  1  4  3  3  1  3.0  3.0  4.0  2.0  3.0  2.0  2.0  NaN   40.0
5   2  5  5  3  5  5  5  2  4.0  4.0  NaN  NaN  NaN  NaN  NaN  NaN   40.0
6   1  3  3  1  3  3  2  1  1.0  2.0  2.0  2.0  2.0  2.0  2.0  1.0   31.0
7   3  4  3  2  4  5  5  3  2.0  4.0  3.0  2.0  NaN  NaN  NaN  NaN   40.0
8   1  2  2  1  1  1  2  1  1.0  1.0  2.0  1.0  1.0  1.0  1.0  1.0   20.0
9   1  2  3  2  2  2  2  1  2.0  2.0  2.0  2.0  2.0  3.0  2.0  1.0   31.0
10  2  6  6  3  4  2  4  2  6.0  5.0  NaN  NaN  NaN  NaN  NaN  NaN   40.0
11  1  2  1  1  2  1  3  1  1.0  1.0  2.0  2.0  1.0  1.0  2.0  1.0   23.0
12  2  3  4  2  2  1  2  2  3.0  2.0  3.0  4.0  3.0  3.0  3.0  NaN   39.0
13  2  3  2  1  3  2  3  2  2.0  1.0  1.0  2.0  3.0  4.0  NaN  NaN   31.0
14  1  4  3  1  2  1  3  2  3.0  2.0  4.0  5.0  6.0  3.0  NaN  NaN   40.0
15  3  6  8  4  5  3  5  6  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   40.0
16  1  3  1  2  3  3  3  1  2.0  3.0  3.0  4.0  4.0  3.0  2.0  1.0   39.0
17  1  3  2  1  1  1  2  1  2.0  2.0  1.0  2.0  2.0  2.0  NaN  NaN   23.0
18  2  3  4  3  2  1  1  2  3.0  3.0  1.0  4.0  4.0  3.0  2.0  1.0   39.0
19  1  4  3  3  1  2  2  3  2.0  3.0  2.0  4.0  3.0  4.0  3.0  NaN   40.0
20  1  2  3  2  2  2  1  1  1.0  3.0  2.0  3.0  3.0  2.0  2.0  1.0   31.0

### a. Double Exponential Smoothing (DES) estimations

In [ ]:
# rename columns
import numpy as np
grocery = grocery_old.iloc[:,0:16]
grocery.columns = np.arange(1,17)
#grocery = grocery.add_prefix("hour")
grocery.head(20)

    1   2   3   4   5   6   7   8    9    10   11   12   13   14   15   16
1    2   4   4   2   4   2   4   1  5.0  4.0  5.0  3.0  NaN  NaN  NaN  NaN
2    3   4   4   5   4   5   4   2  4.0  5.0  NaN  NaN  NaN  NaN  NaN  NaN
3    1   3   2   2   3   6   4   2  3.0  3.0  3.0  4.0  2.0  2.0  NaN  NaN
4    2   3   4   1   4   3   3   1  3.0  3.0  4.0  2.0  3.0  2.0  2.0  NaN
5    2   5   5   3   5   5   5   2  4.0  4.0  NaN  NaN  NaN  NaN  NaN  NaN
6    1   3   3   1   3   3   2   1  1.0  2.0  2.0  2.0  2.0  2.0  2.0  1.0
7    3   4   3   2   4   5   5   3  2.0  4.0  3.0  2.0  NaN  NaN  NaN  NaN
8    1   2   2   1   1   1   2   1  1.0  1.0  2.0  1.0  1.0  1.0  1.0  1.0
9    1   2   3   2   2   2   2   1  2.0  2.0  2.0  2.0  2.0  3.0  2.0  1.0
10   2   6   6   3   4   2   4   2  6.0  5.0  NaN  NaN  NaN  NaN  NaN  NaN
11   1   2   1   1   2   1   3   1  1.0  1.0  2.0  2.0  1.0  1.0  2.0  1.0
12   2   3   4   2   2   1   2   2  3.0  2.0  3.0  4.0  3.0  3.0  3.0  NaN
13   2   3   2   1   3   2   3   2  2.0  1.0  1.0  2.0  3.0  4.0  NaN  NaN
14   1   4   3   1   2   1   3   2  3.0  2.0  4.0  5.0  6.0  3.0  NaN  NaN
15   3   6   8   4   5   3   5   6  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
16   1   3   1   2   3   3   3   1  2.0  3.0  3.0  4.0  4.0  3.0  2.0  1.0
17   1   3   2   1   1   1   2   1  2.0  2.0  1.0  2.0  2.0  2.0  NaN  NaN
18   2   3   4   3   2   1   1   2  3.0  3.0  1.0  4.0  4.0  3.0  2.0  1.0
19   1   4   3   3   1   2   2   3  2.0  3.0  2.0  4.0  3.0  4.0  3.0  NaN
20   1   2   3   2   2   2   1   1  1.0  3.0  2.0  3.0  3.0  2.0  2.0  1.0

In [ ]:
grocery_new = grocery.copy()

In [ ]:
# adjust the grocery data of sales by removing the sales possibly affected by out-of-stock
# check at which hour the demand becomes censored
# note that most summarize methods could be applied row-wise with axis = 1
df_count= grocery_new.count(axis=1)
for i in range(1,21):
    if grocery_new.isnull().any(axis = 1).loc[i]: # with or without = True makes no difference
        # also works: grocery_new.iloc[:,-1].isnull()
        grocery_new.loc[i,df_count[i]] = np.nan
# verify that capturing hour the demand becomes censored
df_count

1     12
2     10
3     14
4     15
5     10
6     16
7     12
8     16
9     16
10    10
11    16
12    15
13    14
14    14
15     8
16    16
17    14
18    16
19    15
20    16
dtype: int64

In [ ]:
grocery

    1   2   3   4   5   6   7   8    9    10   11   12   13   14   15   16
1    2   4   4   2   4   2   4   1  5.0  4.0  5.0  3.0  NaN  NaN  NaN  NaN
2    3   4   4   5   4   5   4   2  4.0  5.0  NaN  NaN  NaN  NaN  NaN  NaN
3    1   3   2   2   3   6   4   2  3.0  3.0  3.0  4.0  2.0  2.0  NaN  NaN
4    2   3   4   1   4   3   3   1  3.0  3.0  4.0  2.0  3.0  2.0  2.0  NaN
5    2   5   5   3   5   5   5   2  4.0  4.0  NaN  NaN  NaN  NaN  NaN  NaN
6    1   3   3   1   3   3   2   1  1.0  2.0  2.0  2.0  2.0  2.0  2.0  1.0
7    3   4   3   2   4   5   5   3  2.0  4.0  3.0  2.0  NaN  NaN  NaN  NaN
8    1   2   2   1   1   1   2   1  1.0  1.0  2.0  1.0  1.0  1.0  1.0  1.0
9    1   2   3   2   2   2   2   1  2.0  2.0  2.0  2.0  2.0  3.0  2.0  1.0
10   2   6   6   3   4   2   4   2  6.0  5.0  NaN  NaN  NaN  NaN  NaN  NaN
11   1   2   1   1   2   1   3   1  1.0  1.0  2.0  2.0  1.0  1.0  2.0  1.0
12   2   3   4   2   2   1   2   2  3.0  2.0  3.0  4.0  3.0  3.0  3.0  NaN
13   2   3   2   1   3   2   3   2  2.0  1.0  1.0  2.0  3.0  4.0  NaN  NaN
14   1   4   3   1   2   1   3   2  3.0  2.0  4.0  5.0  6.0  3.0  NaN  NaN
15   3   6   8   4   5   3   5   6  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
16   1   3   1   2   3   3   3   1  2.0  3.0  3.0  4.0  4.0  3.0  2.0  1.0
17   1   3   2   1   1   1   2   1  2.0  2.0  1.0  2.0  2.0  2.0  NaN  NaN
18   2   3   4   3   2   1   1   2  3.0  3.0  1.0  4.0  4.0  3.0  2.0  1.0
19   1   4   3   3   1   2   2   3  2.0  3.0  2.0  4.0  3.0  4.0  3.0  NaN
20   1   2   3   2   2   2   1   1  1.0  3.0  2.0  3.0  3.0  2.0  2.0  1.0

In [ ]:
grocery_new

    1   2   3   4   5   6   7    8    9    10   11   12   13   14   15   16
1    2   4   4   2   4   2   4  1.0  5.0  4.0  5.0  NaN  NaN  NaN  NaN  NaN
2    3   4   4   5   4   5   4  2.0  4.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    1   3   2   2   3   6   4  2.0  3.0  3.0  3.0  4.0  2.0  NaN  NaN  NaN
4    2   3   4   1   4   3   3  1.0  3.0  3.0  4.0  2.0  3.0  2.0  NaN  NaN
5    2   5   5   3   5   5   5  2.0  4.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN
6    1   3   3   1   3   3   2  1.0  1.0  2.0  2.0  2.0  2.0  2.0  2.0  1.0
7    3   4   3   2   4   5   5  3.0  2.0  4.0  3.0  NaN  NaN  NaN  NaN  NaN
8    1   2   2   1   1   1   2  1.0  1.0  1.0  2.0  1.0  1.0  1.0  1.0  1.0
9    1   2   3   2   2   2   2  1.0  2.0  2.0  2.0  2.0  2.0  3.0  2.0  1.0
10   2   6   6   3   4   2   4  2.0  6.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN
11   1   2   1   1   2   1   3  1.0  1.0  1.0  2.0  2.0  1.0  1.0  2.0  1.0
12   2   3   4   2   2   1   2  2.0  3.0  2.0  3.0  4.0  3.0  3.0  NaN  NaN
13   2   3   2   1   3   2   3  2.0  2.0  1.0  1.0  2.0  3.0  NaN  NaN  NaN
14   1   4   3   1   2   1   3  2.0  3.0  2.0  4.0  5.0  6.0  NaN  NaN  NaN
15   3   6   8   4   5   3   5  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
16   1   3   1   2   3   3   3  1.0  2.0  3.0  3.0  4.0  4.0  3.0  2.0  1.0
17   1   3   2   1   1   1   2  1.0  2.0  2.0  1.0  2.0  2.0  NaN  NaN  NaN
18   2   3   4   3   2   1   1  2.0  3.0  3.0  1.0  4.0  4.0  3.0  2.0  1.0
19   1   4   3   3   1   2   2  3.0  2.0  3.0  2.0  4.0  3.0  4.0  NaN  NaN
20   1   2   3   2   2   2   1  1.0  1.0  3.0  2.0  3.0  3.0  2.0  2.0  1.0

In [ ]:
grocery_new = np.cumsum(grocery_new,axis=1)
grocery_new

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
1,2.0,6.0,10.0,12.0,16.0,18.0,22.0,23.0,28.0,32.0,37.0,NaN,NaN,NaN,NaN,NaN
2,3.0,7.0,11.0,16.0,20.0,25.0,29.0,31.0,35.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,4.0,6.0,8.0,11.0,17.0,21.0,23.0,26.0,29.0,32.0,36.0,38.0,NaN,NaN,NaN
4,2.0,5.0,9.0,10.0,14.0,17.0,20.0,21.0,24.0,27.0,31.0,33.0,36.0,38.0,NaN,NaN
5,2.0,7.0,12.0,15.0,20.0,25.0,30.0,32.0,36.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1.0,4.0,7.0,8.0,11.0,14.0,16.0,17.0,18.0,20.0,22.0,24.0,26.0,28.0,30.0,31.0
7,3.0,7.0,10.0,12.0,16.0,21.0,26.0,29.0,31.0,35.0,38.0,NaN,NaN,NaN,NaN,NaN
8,1.0,3.0,5.0,6.0,7.0,8.0,10.0,11.0,12.0,13.0,15.0,16.0,17.0,18.0,19.0,20.0
9,1.0,3.0,6.0,8.0,10.0,12.0,14.0,15.0,17.0,19.0,21.0,23.0,25.0,28.0,30.0,31.0
10,2.0,8.0,14.0,17.0,21.0,23.0,27.0,29.0,35.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1.0,3.0,4.0,5.0,7.0,8.0,11.0,12.0,13.0,14.0,16.0,18.0,19.0,20.0,22.0,23.0
12,2.0,5.0,9.0,11.0,13.0,14.0,16.0,18.0,21.0,23.0,26.0,30.0,33.0,36.0,NaN,NaN
13,2.0,5.0,7.0,8.0,11.0,13.0,16.0,18.0,20.0,21.0,22.0,24.0,27.0,NaN,NaN,NaN
14,1.0,5.0,8.0,9.0,11.0,12.0,15.0,17.0,20.0,22.0,26.0,31.0,37.0,NaN,NaN,NaN
15,3.0,9.0,17.0,21.0,26.0,29.0,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1.0,4.0,5.0,7.0,10.0,13.0,16.0,17.0,19.0,22.0,25.0,29.0,33.0,36.0,38.0,39.0
17,1.0,4.0,6.0,7.0,8.0,9.0,11.0,12.0,14.0,16.0,17.0,19.0,21.0,NaN,NaN,NaN
18,2.0,5.0,9.0,12.0,14.0,15.0,16.0,18.0,21.0,24.0,25.0,29.0,33.0,36.0,38.0,39.0
19,1.0,5.0,8.0,11.0,12.0,14.0,16.0,19.0,21.0,24.0,26.0,30.0,33.0,37.0,NaN,NaN
20,1.0,3.0,6.0,8.0,10.0,12.0,13.0,14.0,15.0,18.0,20.0,23.0,26.0,28.0,30.0,31.0

In [ ]:
grocery_new['censored'] = grocery_new[16].isna()

In [ ]:
df_des = grocery_new[grocery_new.censored].drop('censored',axis=1)
df_des

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
1,2.0,6.0,10.0,12.0,16.0,18.0,22.0,23.0,28.0,32.0,37.0,NaN,NaN,NaN,NaN,NaN
2,3.0,7.0,11.0,16.0,20.0,25.0,29.0,31.0,35.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,4.0,6.0,8.0,11.0,17.0,21.0,23.0,26.0,29.0,32.0,36.0,38.0,NaN,NaN,NaN
4,2.0,5.0,9.0,10.0,14.0,17.0,20.0,21.0,24.0,27.0,31.0,33.0,36.0,38.0,NaN,NaN
5,2.0,7.0,12.0,15.0,20.0,25.0,30.0,32.0,36.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,3.0,7.0,10.0,12.0,16.0,21.0,26.0,29.0,31.0,35.0,38.0,NaN,NaN,NaN,NaN,NaN
10,2.0,8.0,14.0,17.0,21.0,23.0,27.0,29.0,35.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2.0,5.0,9.0,11.0,13.0,14.0,16.0,18.0,21.0,23.0,26.0,30.0,33.0,36.0,NaN,NaN
13,2.0,5.0,7.0,8.0,11.0,13.0,16.0,18.0,20.0,21.0,22.0,24.0,27.0,NaN,NaN,NaN
14,1.0,5.0,8.0,9.0,11.0,12.0,15.0,17.0,20.0,22.0,26.0,31.0,37.0,NaN,NaN,NaN
15,3.0,9.0,17.0,21.0,26.0,29.0,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,1.0,4.0,6.0,7.0,8.0,9.0,11.0,12.0,14.0,16.0,17.0,19.0,21.0,NaN,NaN,NaN
19,1.0,5.0,8.0,11.0,12.0,14.0,16.0,19.0,21.0,24.0,26.0,30.0,33.0,37.0,NaN,NaN

In [ ]:
# strategy:
# create a big loop that takes a censored curve as input and fills in the nan's
from sklearn.metrics import mean_squared_error
from statsmodels.tsa.api import ExponentialSmoothing
from itertools import product

# write a function that takes alpha,beta,series as input
# and produces the traning sample MSE
# allow 3 periods for burn-in
def DESMSE(alpha,beta,series):
    return mean_squared_error(series[3:],
                              ExponentialSmoothing(series,trend="add", initialization_method='estimated').fit(smoothing_level = alpha,smoothing_trend = beta).predict(3,series.size-1))

# the function below allows you to construct a dataframe of alpha-beta combinations
def expand_grid(dictionary):
   return pd.DataFrame([row for row in product(*dictionary.values())],
                       columns=dictionary.keys())

# define the alpha and beta values to try as a dictionary
dictionary = {'alpha': np.arange(0.1, 1.1, 0.1),
              'beta': np.arange(0.1, 1.1, 0.1)}


# predict curve by curve
# note: the shape attribute for numpy arrays returns the dimensions of the array. If a df has n rows and m columns, then df.shape is (n,m). So Y.shape[0] is n
for row_number in np.arange(0,df_des.shape[0]):
    # take out a censored curve, drop nan values
    temp = df_des.iloc[row_number,:].dropna().reset_index(drop=True)

    # convert cumulative booking into daily booking
    # .diff() will work too
    # temp[1:] gets booking vlaues for days 2-16, temp[:-1] gets booking vlaues for days 1-15,
    temp = np.append(temp[0],temp[1:].values - temp[:-1].values)

    # construct alpha,beta values to try
    des_results = expand_grid(dictionary)

    # add a column called mse, as a place holder for putting in the MSE results later
    des_results["mse"] = np.repeat(0,len(des_results))

    # reuse the DESMSE function above to cycle through all alpha beta values
    # (alpha,beta,series) = (alpha,beta,temp)
    for alpha in np.arange(0.1, 1.1, 0.1):
        for beta in np.arange(0.1, 1.1, 0.1):
           des_results.loc[(des_results["alpha"] == alpha) & (des_results["beta"] == beta),"mse"] = DESMSE(alpha,beta,temp)

    # find the best (alpha beta): sort and put on row 1
    des_results = des_results.sort_values("mse")

    # use the best (alpha,beta) to forecast for the censored days
    # post results onto df_des
    # forecast(16-temp.size) ensures that we forecast the censored days
    predicted_daily_arrival = ExponentialSmoothing(temp,trend="add", initialization_method='estimated'). \
                                         fit(smoothing_level = des_results.iloc[0,0],
                                             smoothing_trend = des_results.iloc[0,1]). \
                                         forecast(16-temp.size)

    # cumsum the daily arrival and add back to the last value that's not nan
    df_des.iloc[row_number,temp.size:] = predicted_daily_arrival.cumsum() + df_des.iloc[row_number,temp.size-1]

In [ ]:
df_des

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
1,2.0,6.0,10.0,12.0,16.0,18.0,22.0,23.000000,28.000000,32.000000,37.000000,41.213765,45.572536,50.076313,54.725097,59.518887
2,3.0,7.0,11.0,16.0,20.0,25.0,29.0,31.000000,35.000000,38.730226,42.425552,46.085980,49.711508,53.302137,56.857866,60.378697
3,1.0,4.0,6.0,8.0,11.0,17.0,21.0,23.000000,26.000000,29.000000,32.000000,36.000000,38.000000,41.484644,45.042991,48.675040
4,2.0,5.0,9.0,10.0,14.0,17.0,20.0,21.000000,24.000000,27.000000,31.000000,33.000000,36.000000,38.000000,40.656035,43.302608
5,2.0,7.0,12.0,15.0,20.0,25.0,30.0,32.000000,36.000000,40.094659,44.204113,48.328362,52.467405,56.621242,60.789874,64.973301
7,3.0,7.0,10.0,12.0,16.0,21.0,26.0,29.000000,31.000000,35.000000,38.000000,41.466845,44.933120,48.398825,51.863958,55.328522
10,2.0,8.0,14.0,17.0,21.0,23.0,27.0,29.000000,35.000000,38.780462,42.540992,46.281591,50.002259,53.702995,57.383800,61.044674
12,2.0,5.0,9.0,11.0,13.0,14.0,16.0,18.000000,21.000000,23.000000,26.000000,30.000000,33.000000,36.000000,38.985114,42.029603
13,2.0,5.0,7.0,8.0,11.0,13.0,16.0,18.000000,20.000000,21.000000,22.000000,24.000000,27.000000,28.870611,30.713163,32.527658
14,1.0,5.0,8.0,9.0,11.0,12.0,15.0,17.000000,20.000000,22.000000,26.000000,31.000000,37.000000,43.031975,50.183874,58.455696
15,3.0,9.0,17.0,21.0,26.0,29.0,34.0,38.427314,42.744369,46.951164,51.047699,55.033975,58.909991,62.675747,66.331244,69.876481
17,1.0,4.0,6.0,7.0,8.0,9.0,11.0,12.000000,14.000000,16.000000,17.000000,19.000000,21.000000,22.683118,24.377946,26.084484
19,1.0,5.0,8.0,11.0,12.0,14.0,16.0,19.000000,21.000000,24.000000,26.000000,30.000000,33.000000,37.000000,40.295246,43.681550

In [ ]:
grocery

    1   2   3   4   5   6   7   8    9    10   11   12   13   14   15   16
1    2   4   4   2   4   2   4   1  5.0  4.0  5.0  3.0  NaN  NaN  NaN  NaN
2    3   4   4   5   4   5   4   2  4.0  5.0  NaN  NaN  NaN  NaN  NaN  NaN
3    1   3   2   2   3   6   4   2  3.0  3.0  3.0  4.0  2.0  2.0  NaN  NaN
4    2   3   4   1   4   3   3   1  3.0  3.0  4.0  2.0  3.0  2.0  2.0  NaN
5    2   5   5   3   5   5   5   2  4.0  4.0  NaN  NaN  NaN  NaN  NaN  NaN
6    1   3   3   1   3   3   2   1  1.0  2.0  2.0  2.0  2.0  2.0  2.0  1.0
7    3   4   3   2   4   5   5   3  2.0  4.0  3.0  2.0  NaN  NaN  NaN  NaN
8    1   2   2   1   1   1   2   1  1.0  1.0  2.0  1.0  1.0  1.0  1.0  1.0
9    1   2   3   2   2   2   2   1  2.0  2.0  2.0  2.0  2.0  3.0  2.0  1.0
10   2   6   6   3   4   2   4   2  6.0  5.0  NaN  NaN  NaN  NaN  NaN  NaN
11   1   2   1   1   2   1   3   1  1.0  1.0  2.0  2.0  1.0  1.0  2.0  1.0
12   2   3   4   2   2   1   2   2  3.0  2.0  3.0  4.0  3.0  3.0  3.0  NaN
13   2   3   2   1   3   2   3   2  2.0  1.0  1.0  2.0  3.0  4.0  NaN  NaN
14   1   4   3   1   2   1   3   2  3.0  2.0  4.0  5.0  6.0  3.0  NaN  NaN
15   3   6   8   4   5   3   5   6  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
16   1   3   1   2   3   3   3   1  2.0  3.0  3.0  4.0  4.0  3.0  2.0  1.0
17   1   3   2   1   1   1   2   1  2.0  2.0  1.0  2.0  2.0  2.0  NaN  NaN
18   2   3   4   3   2   1   1   2  3.0  3.0  1.0  4.0  4.0  3.0  2.0  1.0
19   1   4   3   3   1   2   2   3  2.0  3.0  2.0  4.0  3.0  4.0  3.0  NaN
20   1   2   3   2   2   2   1   1  1.0  3.0  2.0  3.0  3.0  2.0  2.0  1.0

In [ ]:
grocery_old['censored'] = grocery_old[16].isna()

In [ ]:
grocery_old

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,Total,censored
1,2,4,4,2,4,2,4,1,5.0,4.0,5.0,3.0,NaN,NaN,NaN,NaN,40.0,True
2,3,4,4,5,4,5,4,2,4.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,40.0,True
3,1,3,2,2,3,6,4,2,3.0,3.0,3.0,4.0,2.0,2.0,NaN,NaN,40.0,True
4,2,3,4,1,4,3,3,1,3.0,3.0,4.0,2.0,3.0,2.0,2.0,NaN,40.0,True
5,2,5,5,3,5,5,5,2,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,40.0,True
6,1,3,3,1,3,3,2,1,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,31.0,False
7,3,4,3,2,4,5,5,3,2.0,4.0,3.0,2.0,NaN,NaN,NaN,NaN,40.0,True
8,1,2,2,1,1,1,2,1,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,20.0,False
9,1,2,3,2,2,2,2,1,2.0,2.0,2.0,2.0,2.0,3.0,2.0,1.0,31.0,False
10,2,6,6,3,4,2,4,2,6.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,40.0,True
11,1,2,1,1,2,1,3,1,1.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,23.0,False
12,2,3,4,2,2,1,2,2,3.0,2.0,3.0,4.0,3.0,3.0,3.0,NaN,39.0,True
13,2,3,2,1,3,2,3,2,2.0,1.0,1.0,2.0,3.0,4.0,NaN,NaN,31.0,True
14,1,4,3,1,2,1,3,2,3.0,2.0,4.0,5.0,6.0,3.0,NaN,NaN,40.0,True
15,3,6,8,4,5,3,5,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,True
16,1,3,1,2,3,3,3,1,2.0,3.0,3.0,4.0,4.0,3.0,2.0,1.0,39.0,False
17,1,3,2,1,1,1,2,1,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,23.0,True
18,2,3,4,3,2,1,1,2,3.0,3.0,1.0,4.0,4.0,3.0,2.0,1.0,39.0,False
19,1,4,3,3,1,2,2,3,2.0,3.0,2.0,4.0,3.0,4.0,3.0,NaN,40.0,True
20,1,2,3,2,2,2,1,1,1.0,3.0,2.0,3.0,3.0,2.0,2.0,1.0,31.0,False

In [ ]:
grocery_old['des'] = grocery_old[16]
grocery_old.loc[grocery_old.censored,'des'] = df_des[16].round()
grocery_old.head(20)

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,Total,censored,des
1,2,4,4,2,4,2,4,1,5.0,4.0,5.0,3.0,NaN,NaN,NaN,NaN,40.0,True,60.0
2,3,4,4,5,4,5,4,2,4.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,40.0,True,60.0
3,1,3,2,2,3,6,4,2,3.0,3.0,3.0,4.0,2.0,2.0,NaN,NaN,40.0,True,49.0
4,2,3,4,1,4,3,3,1,3.0,3.0,4.0,2.0,3.0,2.0,2.0,NaN,40.0,True,43.0
5,2,5,5,3,5,5,5,2,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,40.0,True,65.0
6,1,3,3,1,3,3,2,1,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,31.0,False,1.0
7,3,4,3,2,4,5,5,3,2.0,4.0,3.0,2.0,NaN,NaN,NaN,NaN,40.0,True,55.0
8,1,2,2,1,1,1,2,1,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,20.0,False,1.0
9,1,2,3,2,2,2,2,1,2.0,2.0,2.0,2.0,2.0,3.0,2.0,1.0,31.0,False,1.0
10,2,6,6,3,4,2,4,2,6.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,40.0,True,61.0
11,1,2,1,1,2,1,3,1,1.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,23.0,False,1.0
12,2,3,4,2,2,1,2,2,3.0,2.0,3.0,4.0,3.0,3.0,3.0,NaN,39.0,True,42.0
13,2,3,2,1,3,2,3,2,2.0,1.0,1.0,2.0,3.0,4.0,NaN,NaN,31.0,True,33.0
14,1,4,3,1,2,1,3,2,3.0,2.0,4.0,5.0,6.0,3.0,NaN,NaN,40.0,True,58.0
15,3,6,8,4,5,3,5,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,True,70.0
16,1,3,1,2,3,3,3,1,2.0,3.0,3.0,4.0,4.0,3.0,2.0,1.0,39.0,False,1.0
17,1,3,2,1,1,1,2,1,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,23.0,True,26.0
18,2,3,4,3,2,1,1,2,3.0,3.0,1.0,4.0,4.0,3.0,2.0,1.0,39.0,False,1.0
19,1,4,3,3,1,2,2,3,2.0,3.0,2.0,4.0,3.0,4.0,3.0,NaN,40.0,True,44.0
20,1,2,3,2,2,2,1,1,1.0,3.0,2.0,3.0,3.0,2.0,2.0,1.0,31.0,False,1.0

In [ ]:
grocery_old['des_1'] = grocery_new[16]
grocery_old.loc[grocery_old.censored,'des'] = df_des[16].round()
grocery_old.head(20)

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,Total,censored,des,des_1
1,2,4,4,2,4,2,4,1,5.0,4.0,5.0,3.0,NaN,NaN,NaN,NaN,40.0,True,60.0,NaN
2,3,4,4,5,4,5,4,2,4.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,40.0,True,60.0,NaN
3,1,3,2,2,3,6,4,2,3.0,3.0,3.0,4.0,2.0,2.0,NaN,NaN,40.0,True,49.0,NaN
4,2,3,4,1,4,3,3,1,3.0,3.0,4.0,2.0,3.0,2.0,2.0,NaN,40.0,True,43.0,NaN
5,2,5,5,3,5,5,5,2,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,40.0,True,65.0,NaN
6,1,3,3,1,3,3,2,1,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,31.0,False,1.0,31.0
7,3,4,3,2,4,5,5,3,2.0,4.0,3.0,2.0,NaN,NaN,NaN,NaN,40.0,True,55.0,NaN
8,1,2,2,1,1,1,2,1,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,20.0,False,1.0,20.0
9,1,2,3,2,2,2,2,1,2.0,2.0,2.0,2.0,2.0,3.0,2.0,1.0,31.0,False,1.0,31.0
10,2,6,6,3,4,2,4,2,6.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,40.0,True,61.0,NaN
11,1,2,1,1,2,1,3,1,1.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,23.0,False,1.0,23.0
12,2,3,4,2,2,1,2,2,3.0,2.0,3.0,4.0,3.0,3.0,3.0,NaN,39.0,True,42.0,NaN
13,2,3,2,1,3,2,3,2,2.0,1.0,1.0,2.0,3.0,4.0,NaN,NaN,31.0,True,33.0,NaN
14,1,4,3,1,2,1,3,2,3.0,2.0,4.0,5.0,6.0,3.0,NaN,NaN,40.0,True,58.0,NaN
15,3,6,8,4,5,3,5,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,True,70.0,NaN
16,1,3,1,2,3,3,3,1,2.0,3.0,3.0,4.0,4.0,3.0,2.0,1.0,39.0,False,1.0,39.0
17,1,3,2,1,1,1,2,1,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,23.0,True,26.0,NaN
18,2,3,4,3,2,1,1,2,3.0,3.0,1.0,4.0,4.0,3.0,2.0,1.0,39.0,False,1.0,39.0
19,1,4,3,3,1,2,2,3,2.0,3.0,2.0,4.0,3.0,4.0,3.0,NaN,40.0,True,44.0,NaN
20,1,2,3,2,2,2,1,1,1.0,3.0,2.0,3.0,3.0,2.0,2.0,1.0,31.0,False,1.0,31.0

In [ ]:
grocery_old['des_3'] = grocery_old['des_1'].fillna(grocery_old['des'])
grocery_old.drop(columns=['des_1', 'des'], inplace=True)
grocery_old = grocery_old.rename(columns={'des_3':'des'})
grocery_old

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,Total,censored,des
1,2,4,4,2,4,2,4,1,5.0,4.0,5.0,3.0,NaN,NaN,NaN,NaN,40.0,True,60.0
2,3,4,4,5,4,5,4,2,4.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,40.0,True,60.0
3,1,3,2,2,3,6,4,2,3.0,3.0,3.0,4.0,2.0,2.0,NaN,NaN,40.0,True,49.0
4,2,3,4,1,4,3,3,1,3.0,3.0,4.0,2.0,3.0,2.0,2.0,NaN,40.0,True,43.0
5,2,5,5,3,5,5,5,2,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,40.0,True,65.0
6,1,3,3,1,3,3,2,1,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,31.0,False,31.0
7,3,4,3,2,4,5,5,3,2.0,4.0,3.0,2.0,NaN,NaN,NaN,NaN,40.0,True,55.0
8,1,2,2,1,1,1,2,1,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,20.0,False,20.0
9,1,2,3,2,2,2,2,1,2.0,2.0,2.0,2.0,2.0,3.0,2.0,1.0,31.0,False,31.0
10,2,6,6,3,4,2,4,2,6.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,40.0,True,61.0
11,1,2,1,1,2,1,3,1,1.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,23.0,False,23.0
12,2,3,4,2,2,1,2,2,3.0,2.0,3.0,4.0,3.0,3.0,3.0,NaN,39.0,True,42.0
13,2,3,2,1,3,2,3,2,2.0,1.0,1.0,2.0,3.0,4.0,NaN,NaN,31.0,True,33.0
14,1,4,3,1,2,1,3,2,3.0,2.0,4.0,5.0,6.0,3.0,NaN,NaN,40.0,True,58.0
15,3,6,8,4,5,3,5,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,True,70.0
16,1,3,1,2,3,3,3,1,2.0,3.0,3.0,4.0,4.0,3.0,2.0,1.0,39.0,False,39.0
17,1,3,2,1,1,1,2,1,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,23.0,True,26.0
18,2,3,4,3,2,1,1,2,3.0,3.0,1.0,4.0,4.0,3.0,2.0,1.0,39.0,False,39.0
19,1,4,3,3,1,2,2,3,2.0,3.0,2.0,4.0,3.0,4.0,3.0,NaN,40.0,True,44.0
20,1,2,3,2,2,2,1,1,1.0,3.0,2.0,3.0,3.0,2.0,2.0,1.0,31.0,False,31.0

### b. Averaging method estimations

In [ ]:
grocery_2 = grocery_old.copy()

In [ ]:
grocery_2 = grocery_2.drop(['censored','des','Total'],axis=1)

In [ ]:
grocery_2.columns = np.arange(1,17)
grocery_2 = pd.melt(grocery_2.reset_index(),id_vars='index',var_name = 'hour',value_name='grocery')
# sort by curve and day
grocery_2 = grocery_2.sort_values(by=['index','hour'])
# ensure conversion done as expected
grocery_2

     index hour  grocery
0        1    1      2.0
20       1    2      4.0
40       1    3      4.0
60       1    4      2.0
80       1    5      4.0
..     ...  ...      ...
239     20   12      3.0
259     20   13      3.0
279     20   14      2.0
299     20   15      2.0
319     20   16      1.0

[320 rows x 3 columns]

In [ ]:
grocery_2['censor'] = grocery_2['grocery'].shift(-1).isna() | grocery_2['grocery'].isna()
grocery_2

     index hour  grocery  censor
0        1    1      2.0   False
20       1    2      4.0   False
40       1    3      4.0   False
60       1    4      2.0   False
80       1    5      4.0   False
..     ...  ...      ...     ...
239     20   12      3.0   False
259     20   13      3.0   False
279     20   14      2.0   False
299     20   15      2.0   False
319     20   16      1.0    True

[320 rows x 4 columns]

这行代码执行了几个操作：

1. `grocery_2['grocery'].shift(-1)`：这部分代码使用了 `shift` 函数来将 `grocery` 列向上移动一行。参数 `-1` 表示向上移动一行，因此这一步将 `grocery` 列中的值向上移动了一行，导致每个值都变成了其下一行的值。

2. `.isna()`：这是 Pandas Series 对象的一个方法，它返回一个布尔值的 Series，表示该 Series 中的每个值是否为缺失值（NaN）。如果值是 NaN，则返回 True，否则返回 False。

3. `grocery_2['grocery'].shift(-1).isna()`：这一部分将步骤1和步骤2组合起来，首先将 `grocery` 列向上移动一行，然后检查每个值是否为 NaN，最终得到一个布尔值的 Series。

这行代码的目的是创建一个布尔值的 Series，该 Series 中的每个值表示相应行的 `grocery` 列是否为缺失值，并且该行的下一行是否为 NaN。

In [ ]:
grocery_2.loc[grocery_2.index[-1], 'censor'] = False

In [ ]:
grocery_2['censor'].value_counts()

censor
False    262
True      58
Name: count, dtype: int64

In [ ]:
grocery_2.fillna(0, inplace=True)
grocery_2

     index hour  grocery  censor
0        1    1      2.0   False
20       1    2      4.0   False
40       1    3      4.0   False
60       1    4      2.0   False
80       1    5      4.0   False
..     ...  ...      ...     ...
239     20   12      3.0   False
259     20   13      3.0   False
279     20   14      2.0   False
299     20   15      2.0   False
319     20   16      1.0   False

[320 rows x 4 columns]

In [ ]:
grocery_2.isna().sum()

index      0
hour       0
grocery    0
censor     0
dtype: int64

In [ ]:
# avg daily booking across uncensored curves
temp = grocery_2[grocery_2.censor==False].groupby('hour').grocery.mean()
temp = temp.reset_index().rename(columns = {'index' : "hour", 'grocery' : 'grocery_avg'})

In [ ]:
# add the daily_booking_avg column to df_avg using pd.merge
temp['hour'] = temp.hour.astype('object')
grocery_2 = pd.merge(grocery_2,temp,how='left',on='hour')
# ensure conversion done as expected
#temp
grocery_2.head(50)
# daily_booking_avg should be the same for each day;
# for example, compare daily_booking_avg of index 1 day 1 and index 2 day 1, index 1 day 2 and index 2 day 2, etc.

    index hour  grocery  censor  grocery_avg
0       1    1      2.0   False     1.650000
1       1    2      4.0   False     3.450000
2       1    3      4.0   False     3.350000
3       1    4      2.0   False     2.100000
4       1    5      4.0   False     2.850000
5       1    6      2.0   False     2.550000
6       1    7      4.0   False     3.000000
7       1    8      1.0   False     1.631579
8       1    9      5.0   False     2.631579
9       1   10      4.0   False     2.437500
10      1   11      5.0   False     2.500000
11      1   12      3.0    True     2.928571
12      1   13      0.0    True     2.785714
13      1   14      0.0    True     2.400000
14      1   15      0.0    True     1.857143
15      1   16      0.0    True     1.000000
16      2    1      3.0   False     1.650000
17      2    2      4.0   False     3.450000
18      2    3      4.0   False     3.350000
19      2    4      5.0   False     2.100000
20      2    5      4.0   False     2.850000
21      2    6      5.0   False     2.550000
22      2    7      4.0   False     3.000000
23      2    8      2.0   False     1.631579
24      2    9      4.0   False     2.631579
25      2   10      5.0    True     2.437500
26      2   11      0.0    True     2.500000
27      2   12      0.0    True     2.928571
28      2   13      0.0    True     2.785714
29      2   14      0.0    True     2.400000
30      2   15      0.0    True     1.857143
31      2   16      0.0    True     1.000000
32      3    1      1.0   False     1.650000
33      3    2      3.0   False     3.450000
34      3    3      2.0   False     3.350000
35      3    4      2.0   False     2.100000
36      3    5      3.0   False     2.850000
37      3    6      6.0   False     2.550000
38      3    7      4.0   False     3.000000
39      3    8      2.0   False     1.631579
40      3    9      3.0   False     2.631579
41      3   10      3.0   False     2.437500
42      3   11      3.0   False     2.500000
43      3   12      4.0   False     2.928571
44      3   13      2.0   False     2.785714
45      3   14      2.0    True     2.400000
46      3   15      0.0    True     1.857143
47      3   16      0.0    True     1.000000
48      4    1      2.0   False     1.650000
49      4    2      3.0   False     3.450000

In [ ]:
# for the censored rows, replace daily_booking with max(actual,average)
# this calculates the unconstrained arrivals amount for the censored periods
grocery_2.loc[grocery_2.censor,'grocery'] = grocery_2.loc[grocery_2.censor,['grocery','grocery_avg']].max(axis=1)

In [ ]:
# Step 3: Repeat alogrithmic steps until you have reached final demand
# update booking by accumulating the updated daily booking
grocery_2['grocery_cumsum'] = grocery_2.groupby('index').grocery.cumsum()
# post results to df_booking
grocery_old['avg'] = grocery_2.groupby('index').grocery_cumsum.tail(1).values.round()
# compare results of AVERAGING and DES method
# averaging method is "less aggressive" than the DES method
grocery_old

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,Total,censored,des,avg
1,2,4,4,2,4,2,4,1,5.0,4.0,5.0,3.0,NaN,NaN,NaN,NaN,40.0,True,60.0,48.0
2,3,4,4,5,4,5,4,2,4.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,40.0,True,60.0,53.0
3,1,3,2,2,3,6,4,2,3.0,3.0,3.0,4.0,2.0,2.0,NaN,NaN,40.0,True,49.0,43.0
4,2,3,4,1,4,3,3,1,3.0,3.0,4.0,2.0,3.0,2.0,2.0,NaN,40.0,True,43.0,41.0
5,2,5,5,3,5,5,5,2,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,40.0,True,65.0,53.0
6,1,3,3,1,3,3,2,1,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,31.0,False,31.0,31.0
7,3,4,3,2,4,5,5,3,2.0,4.0,3.0,2.0,NaN,NaN,NaN,NaN,40.0,True,55.0,49.0
8,1,2,2,1,1,1,2,1,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,20.0,False,20.0,20.0
9,1,2,3,2,2,2,2,1,2.0,2.0,2.0,2.0,2.0,3.0,2.0,1.0,31.0,False,31.0,31.0
10,2,6,6,3,4,2,4,2,6.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,40.0,True,61.0,53.0
11,1,2,1,1,2,1,3,1,1.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,23.0,False,23.0,23.0
12,2,3,4,2,2,1,2,2,3.0,2.0,3.0,4.0,3.0,3.0,3.0,NaN,39.0,True,42.0,40.0
13,2,3,2,1,3,2,3,2,2.0,1.0,1.0,2.0,3.0,4.0,NaN,NaN,31.0,True,33.0,34.0
14,1,4,3,1,2,1,3,2,3.0,2.0,4.0,5.0,6.0,3.0,NaN,NaN,40.0,True,58.0,43.0
15,3,6,8,4,5,3,5,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,True,70.0,59.0
16,1,3,1,2,3,3,3,1,2.0,3.0,3.0,4.0,4.0,3.0,2.0,1.0,39.0,False,39.0,39.0
17,1,3,2,1,1,1,2,1,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,23.0,True,26.0,26.0
18,2,3,4,3,2,1,1,2,3.0,3.0,1.0,4.0,4.0,3.0,2.0,1.0,39.0,False,39.0,39.0
19,1,4,3,3,1,2,2,3,2.0,3.0,2.0,4.0,3.0,4.0,3.0,NaN,40.0,True,44.0,41.0
20,1,2,3,2,2,2,1,1,1.0,3.0,2.0,3.0,3.0,2.0,2.0,1.0,31.0,False,31.0,31.0

### c. Comparing DES and Averaging method results

Comparing the results of the AVERAGING and DES methods from the above table, it's evident that the averaging method is "less aggressive" than the DES method. This indicates that the averaging method, with its simplicity and conservative nature, tends to produce smoother but potentially less accurate forecasts.

The averaging method generates forecasts by computing the average of historical values over a specified period. This approach assumes that future values will resemble the historical average and does not involve intricate smoothing techniques or trend adjustments. Consequently, it yields forecasts that change gradually over time.

In contrast, the DES method incorporates both level and trend components through exponential smoothing. It assigns varying weights to historical observations, giving more importance to recent data points. Moreover, it models the trend in the data, enabling it to capture both short-term fluctuations and long-term trends. Consequently, DES produces forecasts that can respond more rapidly to changes in the data.

Regarding unconstrained prediction, the averaging method tends to be less aggressive due to its conservative reliance on historical averages. It adapts less dynamically to changes compared to DES, leading to smoother and more stable forecasts over time. However, this conservative nature may also result in less accurate predictions, particularly when the data exhibit significant trends or seasonal patterns. revise it and make it a little bot shorter